# Generated by Django 3.2.13 on 2024-07-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('pago', 'Pago'), ('falha', 'Falha')], default='aguardando', max_length=255)),
                ('qr_code', models.CharField(blank=True, max_length=600, null=True)),
                ('amount', models.IntegerField(default=0, help_text='em centavos', verbose_name='valor_transacao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Transacao',
                'verbose_name_plural': 'Transacoes',
            },
        ),
    ]
