# Generated by Django 3.2.13 on 2024-11-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
